sudo: true
dist: bionic
language: node_js
node_js:
  - 12
before_install:
  - sudo apt-get install -y libgmp-dev libmpfr-dev libboost-all-dev
  - curl -L https://github.com/CGAL/cgal/archive/releases/CGAL-5.0.1.tar.gz | tar zx
  - mkdir $TRAVIS_BUILD_DIR/cgal-releases-CGAL-5.0.1/build
  - mkdir $TRAVIS_BUILD_DIR/cgal-releases-CGAL-5.0.1/installed
  - (cd cgal-releases-CGAL-5.0.1/build; cmake -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/cgal-releases-CGAL-5.0.1/installed ..; make install)

env:
  global:
    CGAL_GYP_INCLUDES: $TRAVIS_BUILD_DIR/cgal-releases-CGAL-5.0.1/installed/include
  matrix:
    -
    - GGAL_USE_EPECK=1
