sudo: true
dist: bionic
language: node_js
node_js:
  - 12
before_install:
  - sudo apt-get install -y libgmp-dev libmpfr-dev libboost-all-dev
  - curl -L https://github.com/CGAL/cgal/archive/releases/CGAL-4.14.tar.gz | tar zx
  - mkdir $TRAVIS_BUILD_DIR/cgal-releases-CGAL-4.14/build
  - mkdir $TRAVIS_BUILD_DIR/cgal-releases-CGAL-4.14/installed
  - (cd cgal-releases-CGAL-4.14/build; CXXFLAGS=-fPIC cmake -DBUILD_SHARED_LIBS=FALSE -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/cgal-releases-CGAL-4.14/installed ..; make install)
env:
  global:
    CGAL_GYP_LDFLAGS: -L$TRAVIS_BUILD_DIR/cgal-releases-CGAL-4.14/installed/lib
    CGAL_GYP_INCLUDES: $TRAVIS_BUILD_DIR/cgal-releases-CGAL-4.14/installed/include
  matrix:
    -
    - GGAL_USE_EPECK=1
